version: '3.8'
services:
  php-server:
    image: php:8.2-apache
    container_name: minimal-web-notepad
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    restart: unless-stopped
